// ci_test.go guards the CI workflow hygiene invariants fixed in issue #213:
// tool versions must be pinned (not "@latest"), every branch push must keep
// triggering CI (the Gitea merge gate runs on the GitHub push mirror) with
// duplicate runs deduped via a concurrency group, docs must deploy from main
// as well as tags, the extension unit tests must run in CI, dev scripts must
// stay out of the store zip, and the ghcr :latest tag must not move on
// prerelease tags.
package packaging_test

import (
	"regexp"
	"strings"
	"testing"
)

func readCIWorkflow(t *testing.T) string {
	t.Helper()
	return readRepoFile(t, ".github/workflows/ci.yml")
}

func TestCIWorkflowPinsToolVersions(t *testing.T) {
	ci := readCIWorkflow(t)

	// swag@latest and addons-linter@latest made every run depend on whatever
	// the registry served that day; a new major hard-fails every PR/release.
	if strings.Contains(ci, "@latest") {
		t.Error("ci.yml must not install any tool @latest; pin an exact version (issue #213)")
	}
	if !regexp.MustCompile(`version:\s*v[0-9]+\.[0-9]+`).MatchString(ci) {
		t.Error("ci.yml must pin golangci-lint to an exact version (issue #213)")
	}
	if !regexp.MustCompile(`addons-linter@[0-9]+\.[0-9]+\.[0-9]+`).MatchString(ci) {
		t.Error("ci.yml must pin addons-linter to an exact version (issue #213)")
	}
	// The swagger freshness gate must not install its own swag; the Makefile
	// target supplies the go.mod-pinned version (see TestMakefileSwagger...).
	if strings.Contains(ci, "go install github.com/swaggo/swag") {
		t.Error("ci.yml must not go-install swag; `make swagger` runs the go.mod-pinned version via `go run`")
	}
}

func TestMakefileSwaggerPinMatchesGoMod(t *testing.T) {
	mk := readRepoFile(t, "Makefile")
	gomod := readRepoFile(t, "go.mod")

	// The Makefile must run an exact-version swag via `go run`, not a PATH
	// binary of unknown vintage. (A version-less `go run` cannot work here:
	// the pruned module graph lacks go.sum entries for swag's CLI-only deps.)
	if !strings.Contains(mk, "go run github.com/swaggo/swag/cmd/swag@$(SWAG_VERSION) init") {
		t.Fatal("Makefile swagger target must invoke `go run github.com/swaggo/swag/cmd/swag@$(SWAG_VERSION)` (issue #213)")
	}
	pin := regexp.MustCompile(`(?m)^SWAG_VERSION\s*:?=\s*(v[0-9]+\.[0-9]+\.[0-9]+)`).FindStringSubmatch(mk)
	if pin == nil {
		t.Fatal("Makefile must define SWAG_VERSION as an exact version (issue #213)")
	}
	want := regexp.MustCompile(`(?m)^\s*github\.com/swaggo/swag (v[0-9]+\.[0-9]+\.[0-9]+)`).FindStringSubmatch(gomod)
	if want == nil {
		t.Fatal("go.mod no longer requires github.com/swaggo/swag; update this test and the Makefile pin")
	}
	if pin[1] != want[1] {
		t.Errorf("Makefile SWAG_VERSION %s must match go.mod github.com/swaggo/swag %s — the committed docs/swagger/ was generated by the go.mod version", pin[1], want[1])
	}
}

func TestCIWorkflowTriggersOnEveryBranchPushAndDispatch(t *testing.T) {
	ci := readCIWorkflow(t)

	// CRITICAL: this repo is developed via Gitea PRs and CI runs only on the
	// GitHub push mirror, so branch push runs are the merge gate. Deduping
	// must happen via the concurrency group, never by narrowing push branches.
	if !regexp.MustCompile(`branches:\s*\[\s*"\*\*"\s*\]`).MatchString(ci) {
		t.Error(`ci.yml push trigger must keep branches: ["**"] — branch push runs are the Gitea merge gate (issue #213)`)
	}
	if !regexp.MustCompile(`(?m)^\s+workflow_dispatch:`).MatchString(ci) {
		t.Error("ci.yml must expose workflow_dispatch as a manual rerun/publish lever (issue #213)")
	}
}

func TestCIWorkflowDedupesRunsViaConcurrency(t *testing.T) {
	ci := readCIWorkflow(t)

	if !regexp.MustCompile(`(?m)^concurrency:`).MatchString(ci) {
		t.Error("ci.yml must define a workflow-level concurrency group so push+PR runs of the same commit dedupe (issue #213)")
	}
	// Keyed on the commit SHA (PR head SHA for pull_request events) so the
	// push run and the PR run of the same commit share a group.
	if !strings.Contains(ci, "github.event.pull_request.head.sha") || !strings.Contains(ci, "github.sha") {
		t.Error("ci.yml concurrency group must be keyed on the commit SHA (pull_request.head.sha || sha), not the ref (issue #213)")
	}
	// Tag (release) runs must never be cancelled by a branch push run.
	if !strings.Contains(ci, `cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/') }}`) {
		t.Error("ci.yml concurrency must exempt tag runs from cancel-in-progress so releases cannot be killed mid-flight (issue #213)")
	}
	// Main (like tags) must be keyed by ref, not SHA: a new branch pushed at
	// main's head would otherwise join the in-flight main run's SHA group,
	// cancel it, and silently lose the main docs deploy (PR #250 review).
	if !strings.Contains(ci, `github.ref == 'refs/heads/main') && github.ref`) {
		t.Error("ci.yml concurrency group must key refs/heads/main by ref so cross-ref SHA collisions cannot cancel a main run (PR #250 review)")
	}
}

func TestCIWorkflowSerializesPagesDeployments(t *testing.T) {
	ci := readCIWorkflow(t)

	// The release flow (merge to main, then tag the merge commit) fires two
	// runs in different ci-* concurrency groups, both reaching the docs job.
	// GitHub Pages allows one in-flight deployment, so without a shared
	// job-level group the later deploy-pages call 409s (PR #250 review).
	if !regexp.MustCompile(`(?m)^\s+group: github-pages$`).MatchString(ci) {
		t.Error("ci.yml docs job must declare job-level concurrency group github-pages to serialize Pages deployments (PR #250 review)")
	}
	if !strings.Contains(ci, "cancel-in-progress: false") {
		t.Error("ci.yml docs job concurrency must set cancel-in-progress: false so an in-flight Pages deploy is queued behind, never killed (PR #250 review)")
	}
}

func TestCIWorkflowSwaggerGateCatchesUntrackedFiles(t *testing.T) {
	ci := readCIWorkflow(t)

	// `git diff --exit-code` only sees modified tracked files; a freshly
	// generated but never-committed swagger file sails through without this.
	if !strings.Contains(ci, "git status --porcelain docs/swagger/") {
		t.Error("ci.yml swagger freshness gate must also check `git status --porcelain docs/swagger/` for untracked files (issue #213)")
	}
}

func TestCIWorkflowRunsExtensionUnitTests(t *testing.T) {
	ci := readCIWorkflow(t)

	// The node:test suites added with the extension fixes (PR #237) must run
	// in CI. The shell-expanded glob works on Node < 21, which has no native
	// glob support in `node --test`.
	if !strings.Contains(ci, "node --test integrations/extension/*.test.mjs") {
		t.Error("ci.yml must run the extension unit tests: node --test integrations/extension/*.test.mjs (issue #213, PR #237)")
	}
}

func TestCIWorkflowExcludesDevScriptsFromExtensionZip(t *testing.T) {
	ci := readCIWorkflow(t)

	// icons/generate*.js are Node dev scripts; AMO flags unreferenced files
	// bundled into the store zip (deferred from PR #238).
	if !strings.Contains(ci, `-x "icons/generate*"`) {
		t.Error(`ci.yml extension zip must exclude icons/generate* dev scripts (-x "icons/generate*") (issue #213, PR #238)`)
	}
}

func TestCIWorkflowGatesDockerLatestTag(t *testing.T) {
	ci := readCIWorkflow(t)

	// type=raw,value=latest moved :latest on every tag build, prereleases
	// included; flavor latest=auto only applies it to non-prerelease semver
	// tags (deferred from PR #236).
	if strings.Contains(ci, "type=raw,value=latest") {
		t.Error("ci.yml docker metadata must not force :latest unconditionally; use flavor latest=auto (issue #213, PR #236)")
	}
	if !strings.Contains(ci, "latest=auto") {
		t.Error("ci.yml docker metadata must gate :latest via flavor latest=auto (issue #213, PR #236)")
	}
}

func TestCIWorkflowDeploysDocsFromMain(t *testing.T) {
	ci := readCIWorkflow(t)

	// Docs merged to main used to sit unpublished until the next release tag.
	if !strings.Contains(ci, `startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'`) {
		t.Error("ci.yml docs job must deploy on main pushes as well as tags (issue #213)")
	}
}

func TestCIWorkflowHasCSSFreshnessGate(t *testing.T) {
	ci := readCIWorkflow(t)

	// The committed web/static/css/app.css must be rebuilt whenever templates
	// change Tailwind class usage; without the gate stale CSS ships unstyled
	// UI to anyone running the committed artifact (caught a real instance:
	// missing .tab styles). Mirrors the swagger gate, both halves.
	if !strings.Contains(ci, "git diff --exit-code web/static/css/") {
		t.Error("ci.yml must gate CSS freshness with `git diff --exit-code web/static/css/` (issue #213)")
	}
	if !strings.Contains(ci, "git status --porcelain web/static/css/") {
		t.Error("ci.yml CSS gate must also check `git status --porcelain web/static/css/` for untracked files (issue #213)")
	}
}

func TestCIWorkflowRunsTestsWithRaceDetector(t *testing.T) {
	ci := readCIWorkflow(t)

	// The click pipeline, session middleware, and MCP handler cross
	// goroutines; CI is where the race detector's runtime cost is free.
	if !regexp.MustCompile(`go test\s+-race\s`).MatchString(ci) {
		t.Error("ci.yml test job must run `go test -race ./...` (issue #213)")
	}
}
